In [8]:
import numpy as np

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
#10 even spaced numbers
np.linspace(1,3,10)

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [16]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
#random numbers & random matrix (uniform distribution)
print(np.random.rand(5))
print(np.random.rand(5,2))

[0.08474816 0.51238202 0.11670673 0.74449211 0.05924588]
[[0.04045712 0.07916316]
 [0.5124414  0.13796821]
 [0.36035207 0.93843478]
 [0.57207099 0.95262733]
 [0.5794325  0.41189585]]


In [19]:
#random numbers & random matrix (normal distribution)
print(np.random.randn(5))
print(np.random.randn(5,2))

[ 1.8251443  -0.4340374   2.13736171  0.33890458 -1.42406664]
[[-0.88170501  0.31875798]
 [ 0.37009307 -0.60992737]
 [-1.0600652   1.30886017]
 [ 1.16200212 -0.49046512]
 [-0.46101729 -0.18580233]]


In [21]:
#random numbers
print(np.random.randint(1,100))
print(np.random.randint(1,100,10))

37
[73 74 44 58  4 66 72 36 56 44]


In [22]:
arr = np.arange(0,10)
print(arr)
arr.reshape(5,2)

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
#value , index
print(arr.max(), arr.argmax())
print(arr.min(), arr.argmin())

9 9
0 0


In [25]:
arr.shape

(10,)

In [26]:
arr.dtype

dtype('int64')

In [36]:
arr = np.array([[0,1,2],[3,4,5],[7,8,9]])
print(arr,'\n--------------')
print(arr[:][1:],'\n--------------')
print(arr[:,1:],'\n--------------')

[[0 1 2]
 [3 4 5]
 [7 8 9]] 
--------------
[[3 4 5]
 [7 8 9]] 
--------------
[[1 2]
 [4 5]
 [8 9]] 
--------------


In [39]:
print(arr[:2,1:])

[[1 2]
 [4 5]]


In [41]:
bool_arr = arr > 5
print(bool_arr)

[[False False False]
 [False False False]
 [ True  True  True]]


In [42]:
arr[bool_arr]

array([7, 8, 9])

In [43]:
arr[arr<3]

array([0, 1, 2])

In [52]:
arr_1 = np.arange(0,10)
arr_2 = np.arange(0,20,2)
print(arr_1)
print(arr_2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [57]:
print(arr_1 * arr_2)
print(arr_1**2 / arr_2)
print(arr_1 / arr_2)

[  0   2   8  18  32  50  72  98 128 162]
[nan 0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[nan 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]


/tmp/ipykernel_24982/1593492552.py:2: RuntimeWarning: invalid value encountered in divide
  print(arr_1**2 / arr_2)
/tmp/ipykernel_24982/1593492552.py:3: RuntimeWarning: invalid value encountered in divide
  print(arr_1 / arr_2)
